spring:
  batch:
    initialize-schema: always
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/batch_demo
    username: batch_demo
    password: batch_demo